Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2020-06, with the labels that each got.

#178 Regenerate id_case if district code address is changed.
  api/cases/handlers.js
  api/cases/route_prerequesites.js
  api/cases/routes.js
  services/cases.js
Labels: hotfix

#217 Added filter in cases transfer list.
  helpers/casetransferhelper.js
  services/cases_transfers.js
Labels: enhancement

#236 Fix cases list sorting.
  api/cases/validations/input.js
  helpers/custom.js
  services/cases.js
Labels: bug

#234 sort descending in case transfer log.
  helpers/casetransferhelper.js
Labels: enhancement

#243 Refactor casesheet.js (305 lines of code (exceeds 250 allowed)).
  helpers/casesheet/casesheet.js
  helpers/casetransferhelper.js
Labels: refactor

#241 Fix cases list sorting.
  api/cases/validations/input.js
  helpers/custom.js
  services/cases.js
Labels: bug

#242 duplicate code remove and refactoring filter
  helpers/custom.js
  helpers/filter/userfilter.js
  services/users.js
Labels: refactor

#247 Refactor code
  api/cases/handlers.js
  api/cases/route_prerequesites.js
  api/cases/routes.js
  api/cases/validations/input.js
  api/cases_transfers/handlers.js
  api/cases_transfers/index.js
  api/cases_transfers/package.json
  api/cases_transfers/route_prerequesites.js
  api/cases_transfers/routes.js
  api/cases_transfers/validations/input.js
  api/index.js
  helpers/casetransferhelper.js
  models/CaseTransfer.js
  services/cases_transfers.js
Labels: enhancement, refactor

#250 Added a stage filter in cases & cases-transfer list.
  helpers/casetransferhelper.js
  services/cases.js
Labels: enhancement

#251 Allow stage filter in param queries
  api/cases/validations/input.js
Labels: enhancement

#255 Development error handling
  helpers/filter/mapfilter.js
  services/users.js
Labels: bug, enhancement
