Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2020-11, with the labels that each got.

#611 change rate d to a per file
  api/category/handlers.js
  api/category/routes.js
  helpers/request/index.js
  models/Hospital.js
  models/Unit.js
Labels: code quality

#610 Feature/cases verifications
  api/cases/validations/input.js
  api/cases_verifications/handlers.js
  api/cases_verifications/routes.js
  helpers/constant.js
  services/cases.js
  services/cases.v2.js
  services/cases_verifications.js
Labels: enhancement

#615 export demographic
  api/areas/handlers.js
  api/case_dashboard/handlers.js
  api/case_dashboard/index.js
  api/case_dashboard/routes.js
  api/case_dashboard/routes_explode.js
  api/category/handlers.js
  helpers/custom.js
  helpers/request/index.js
Labels: WIP, enhancement

#617 Feature/cases verification (Adjustment based on latest flow)
  helpers/constant.js
  models/Case.js
  services/cases.js
  services/cases.v2.js
  services/cases_verifications.js
Labels: priority high

#619 miss total(export-dashboard):
  api/case_dashboard/handlers.js
Labels: bug

#620 Feature/epidemiological-investigation-form (adjustment layout)
  helpers/pdfmaker.js
  helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
Labels: enhancement

#621 Refactor/dashboard old
  api/case_dashboard/handlers.js
  api/cases/handlers.js
  api/dashboard/handlers.js
  api/dashboard/index.js
  api/dashboard/routes.js
  api/histories/handlers.js
  helpers/aggregate/func/filter.js
  helpers/aggregate/func/index.js
  helpers/constant.js
  helpers/custom.js
  helpers/dashboardbottom.js
  helpers/export/cases/column.js
  helpers/export/cases/lookup.js
  helpers/export/cases/select_column.js
  helpers/export/histories/column.js
  helpers/export/index.js
  helpers/filter/date.js
  helpers/filter/exportfilter.js
  helpers/filter/historyfilter.js
  helpers/request/README.md
  helpers/request/index.js
  helpers/sectionnumber.js
  services/dashboard.js
  services/histories.js
Labels: code quality, refactor, refactoring duplicate code, similar blocks of code

#622 excell/add-column
  api/case_dashboard/handlers.js
Labels: enhancement

#624 add column (dashboard-demographic):
  api/case_dashboard/handlers.js
Labels: enhancement

#625 revision file name export
  api/case_dashboard/handlers.js
Labels: enhancement

#599 Feature/cases import
  api/cases/validations/input.js
  api/v2/cases/handlers.js
  api/v2/cases/route_prerequesites.js
  api/v2/cases/routes.js
  api/v2/cases/validations/input.js
  helpers/cases/flagger.js
  helpers/cases/sheet/config.json
  helpers/cases/sheet/getters/attributes/inspection_support.js
  helpers/cases/sheet/getters/attributes/traveling_history.js
  helpers/cases/sheet/getters/attributes/visited_local_area.js
  helpers/cases/sheet/getters/attributes/visited_public_place.js
  helpers/cases/sheet/getters/case.getters.js
  helpers/cases/sheet/getters/history.getters.js
  helpers/cases/sheet/getters/index.js
  helpers/cases/sheet/handler.js
  helpers/cases/sheet/helper.js
  helpers/cases/sheet/index.js
  helpers/cases/sheet/reference.js
  helpers/cases/sheet/validator.js
  helpers/constant.js
  helpers/custom.js
  helpers/dictionary/id.json
  models/Case.js
  services/cases.v2.js
  services/histories.js
Labels: priority high

#632 fix/flagger wrong field type
  helpers/cases/flagger.js
Labels: bug

#634 Feature/cases import
  api/v2/cases/validations/input.js
  helpers/cases/sheet/getters/attributes/visited_local_area.js
  helpers/cases/sheet/getters/case.getters.js
  helpers/cases/sheet/getters/history.getters.js
  helpers/cases/sheet/helper.js
  helpers/cases/sheet/validator.js
  helpers/dictionary/id.json
Labels: enhancement

#633 Codeclimate/inject
  api/country/handlers.js
  api/histories/handlers.js
  api/histories/routes.js
  api/inject/handlers.js
  api/inject/routes.js
  api/occupations/handlers.js
  api/occupations/routes.js
  api/rdt/handlers.js
  api/rdt/routes.js
  helpers/request/index.js
  helpers/routes/index.js
  services/histories.js
  services/inject.js
  services/rdt.js
Labels: code quality

#638 fix case summary
  api/cases/handlers.js
  services/cases.js
Labels: bug

#646 Hot fixing issue
  models/Case.js
  services/histories.js
Labels: bug, hotfix

#648 aggregate handle null size
  services/cases.v2.js
Labels: bug

#652 hotfix(export-clinic):bug query export clinic info
  helpers/export/cases/select_column.js
  helpers/filter/historyfilter.js
Labels: bug, hotfix

#654 Hot fix/export clinic
  services/histories.js
Labels: bug, hotfix

#657 Hotfix/update history
  services/histories.js
Labels: bug

#667 Feature/detail case summary temp
  helpers/constant.js
  services/cases.v2.js
Labels: enhancement

#665 improvment(dashboard):
  api/case_dashboard/handlers.js
  api/validations.js
  helpers/aggregate/demographicaggregate.js
Labels: backend, enhancement

#672 hot-fix(add-new-column-export):
  helpers/filter/exportfilter.js
Labels: enhancement, hotfix

#673 hot-fix(add-new-column-export):
  helpers/filter/exportfilter.js
Labels: enhancement, hotfix

#675 feature/network-graph-filter
  helpers/filter/casefilter.js
  services/case_related.js
  services/cases.js
Labels: enhancement

#684 Hotfix/export handle undefined
  helpers/custom.js
  helpers/export/cases/column.js
Labels: bug, hotfix

#683 hot-fix(export):
  helpers/custom.js
  helpers/export/cases/column.js
Labels: bug, hotfix

#689 imporove existing sevice: getHistoryByCase
  services/histories.js
Labels: enhancement

#691 Feature/detail case summary
  services/cases.v2.js
Labels: enhancement

#693 example unit models
  api/unit/handlers.js
  api/unit/index.js
  api/unit/routes.js
  models/Unit.js
  services/unit.js
Labels: code quality

#696 bug-fix(areas-hospital):
  services/areas.js
Labels: bug

#698 Feature/improvement map
  api/map/handlers.js
  api/map/routes.js
  helpers/aggregate/mapaggregate.js
  helpers/aggregate/mapgroup.js
  helpers/aggregate/mapsummaryaggregate.js
  helpers/filter/mapfilter.js
  services/map.js
Labels: enhancement

#701 Hotfix/closecontacts
  api/cases/route_prerequesites.js
  helpers/cases/setters.js
  services/cases.js
  services/cases_verifications.js
Labels: bug

#704 Hotfix/closecontacts
  api/cases/route_prerequesites.js
  helpers/cases/setters.js
  services/cases.js
  services/cases_verifications.js
Labels: bug

#705 [Staging] improve inspection_support sheet getter
  helpers/cases/sheet/getters/case.getters.js
Labels: enhancement

#706 [Production] improve inspection_support sheet getter
  helpers/cases/sheet/getters/case.getters.js
Labels: enhancement

#703 trying refactor local transmission
  api/history_travel/handlers.js
  api/history_travel/routes.js
  api/inspection_support/handlers.js
  api/inspection_support/routes.js
  api/local_transmission/handlers.js
  api/local_transmission/routes.js
  helpers/global/crud.js
  services/inspection_support.js
  services/local_transmission.js
Labels: code quality
