Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2020-08, with the labels that each got.

#421 hotfix id-case agar tidak load semua data
  services/cases.js
Labels: bug

#422 hotfix id-case agar tidak load semua data
  services/cases.js
Labels: bug

#423 Refactor Areas service
  api/areas/routes.js
  api/areas/validations/input.js
  api/areas/validations/output.js
  helpers/filter/mapfilter.js
  services/areas.js
Labels: enhancement, refactor

#426 Added case summary badge func.
  api/cases/handlers.js
  helpers/cases/revamp/handlerget.js
  services/case_revamp.js
Labels: enhancement

#425 Pemeriksaan penunjang
  api/category/handlers.js
  api/category/routes.js
  docker-compose.yml
  models/History.js
  models/Specimen.js
  models/index.js
  services/category.js
Labels: backend

#424 edit run script npm nodemon for all Oprating sistem
  package.json
Labels: bug

#427 add field for history factore travelling
  models/History.js
Labels: backend

#431 map case related
  api/case_related/handlers.js
  api/case_related/index.js
  api/case_related/routes.js
  helpers/constant.js
  helpers/filter/relatedfilter.js
  services/case_related.js
Labels: enhancement

#432 Add area
  api/areas/handlers.js
  api/areas/routes.js
  services/areas.js
Labels: enhancement

#434 Feature/map revamp
  helpers/filter/mapfilter.js
  helpers/filter/relatedfilter.js
  services/map.js
Labels: enhancement

#433 Feature/daily report
  api/index.js
  api/reports/handlers.js
  api/reports/index.js
  api/reports/package.json
  api/reports/routes.js
  helpers/filter/dailyreportfilter.js
  helpers/reports/handler.js
  services/index.js
  services/reports.js
Labels: enhancement

#435 Revamp faktor kontak paparan
  api/cases_transfers/validations/input.js
  models/Case.js
  models/History.js
Labels: enhancement, help wanted

#436 Feature/daily report
  helpers/filter/dailyreportfilter.js
  helpers/reports/handler.js
  services/reports.js
Labels: enhancement

#437 Add column closecontact
  models/CloseContact.js
Labels: enhancement

#438 forget use validation Joi
  api/close_contact/validations/input.js
Labels: bug

#440 Feature/district map geo
  helpers/constant.js
  helpers/filter/mapfilter.js
  models/Case.js
  models/DistrictGeo.js
  services/map.js
Labels: enhancement

#439 add filed address factor contact
  models/Case.js
Labels: enhancement

#443 add some rs type and code faskes
  models/Unit.js
Labels: enhancement

#444 change output json, find to aggregate query
  helpers/filter/relatedfilter.js
  services/case_related.js
Labels: enhancement

#445 change output by id_case
  helpers/custom.js
  models/Case.js
  services/case_related.js
  services/map.js
Labels: bug

#449 Feature/daily report
  helpers/filter/dailyreportfilter.js
  helpers/reports/case.js
  helpers/reports/handler.js
  helpers/reports/rdt.js
  helpers/reports/transformer.js
  models/History.js
  services/reports.js
Labels: enhancement

#450 change number to string
  helpers/filter/relatedfilter.js
Labels: bug

#451 Move kotak paparan
  models/Case.js
  models/History.js
Labels: bug

#453 bug fix field miss
  models/History.js
Labels: bug

#455 Added leftover require
  helpers/cases/revamp/handlerget.js
Labels: bug

#456 bug fix rdt findinternal data
  services/rdt.js
Labels: bug

#454 Feature/epidemiological investigation form
  helpers/pdftemplate/components/epidemiological-investigation/close-contact-list.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
  helpers/pdftemplate/components/epidemiological-investigation/diagnosis.js
  helpers/pdftemplate/components/epidemiological-investigation/inspection-information.js
  helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js
  helpers/pdftemplate/layouts/epidemiological-investigation.js
Labels: enhancement

#459 Feature/export excell rev5
  api/cases/handlers.js
  helpers/constant.js
  helpers/custom.js
  helpers/filter/casefilter.js
  helpers/filter/exportfilter.js
  models/Case.js
  services/cases.js
Labels: enhancement

#462 Feature/close contact
  models/CloseContact.js
Labels: enhancement

#460 bug fix can't save rdt
  services/rdt.js
Labels: bug

#464 Bug fix rdt
  api/rdt/validations/input.js
  services/rdt.js
Labels: bug

#465 change logic optimize result
  services/case_related.js
Labels: enhancement

#466 refactor category and add field handling export column
  helpers/custom.js
  helpers/filter/exportfilter.js
  models/Category.js
  services/category.js
Labels: bug, dependencies, enhancement

#467 delete field factor contat
  models/Case.js
Labels: bug

#470 fix rdt multiple insert
  services/rdt.js
Labels: bug

#471 Improved PE Form
  helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
  helpers/pdftemplate/components/epidemiological-investigation/diagnosis.js
  helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js
Labels: enhancement

#469 refactor old version code
  api/occupations/handlers.js
  api/occupations/index.js
  api/occupations/routes.js
  helpers/filter/exportfilter.js
  helpers/paginate.js
  models/Occupation.js
  services/category.js
  services/country.js
  services/map.js
  services/occupations.js
Labels: enhancement, refactor

#473 Feature/daily report
  api/reports/handlers.js
  api/reports/routes.js
  helpers/constant.js
  helpers/filter/dailyreportfilter.js
  helpers/reports/handler.js
  helpers/reports/transformer.js
  services/reports.js
Labels: enhancement

#474 add filter in map
  helpers/filter/mapfilter.js
Labels: enhancement

#475 added preSave histories
  models/History.js
Labels: enhancement

#476 Feature/daily report
  helpers/constant.js
  helpers/filter/dailyreportfilter.js
  helpers/reports/handler.js
  services/reports.js
Labels: enhancement

#477 change timezoe to moment
  helpers/custom.js
Labels: bug

#478 rounding age month
  helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js
Labels: bug
