Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2020-07, with the labels that each got.

#260 add filter default map
  helpers/filter/mapfilter.js
  services/map.js
Labels: enhancement

#254 Remove unused pusher packages.
  .env-example
  config/config.js
  helpers/pusher.js
  package-lock.json
  package.json
Labels: dependencies

#264 bug if unit_id empty
  services/users.js
Labels: bug

#266 typo in string and add schema revamp
  helpers/filter/mapfilter.js
  models/CasesRevamp.js
  models/CloseContact.js
  models/HistoryRevamp.js
Labels: bug, enhancement

#265 Added service for get user by specified username.
  api/users/handlers.js
  api/users/routes.js
  services/users.js
Labels: enhancement

#282 revamp case and change request filter map
  helpers/filter/mapfilter.js
  models/CasesRevamp.js
  models/CloseContact.js
  models/HistoryRevamp.js
  models/index.js
  services/case_revamp.js
  services/map.js
Labels: enhancement

#268 Added complete user fields info
  models/User.js
Labels: enhancement

#285 case related fixing v.1
  api/case_related/handlers.js
  api/case_related/routes.js
  helpers/filter/relatedfilter.js
  models/Case.js
  services/case_related.js
Labels: enhancement

#286 Input case revision
  api/rdt/route_prerequesites.js
  api/rdt/routes.js
  services/histories.js
  services/rdt.js
Labels: enhancement

#287 create revamp laporan kasus
  api/cases_revamp/handlers.js
  api/cases_revamp/index.js
  api/cases_revamp/package.json
  api/cases_revamp/routes.js
  api/index.js
  models/Case.js
  models/CasesRevamp.js
  models/History.js
  models/HistoryRevamp.js
  models/index.js
  services/case_revamp.js
  services/index.js
Labels: enhancement

#302 Feature/case revamp
  api/cases_revamp/handlers.js
  api/cases_revamp/routes.js
  helpers/custom.js
  helpers/filter/exportfilter.js
  models/Case.js
  services/case_revamp.js
Labels: bug, enhancement

#301 Local
  api/users/validations/input.js
  services/users.js
Labels: bug, enhancement

#305 Local
  api/users/validations/input.js
  services/users.js
Labels: hotfix

#306 Feature/case revamp
  helpers/cases/revamp/handlerpost.js
  helpers/constant.js
  models/Case.js
  models/History.js
  services/case_revamp.js
Labels: enhancement

#308 Feature/close contact
  api/close_contact/handlers.js
  api/close_contact/index.js
  api/close_contact/package.json
  api/close_contact/route_prerequesites.js
  api/close_contact/routes.js
  api/close_contact/validations/input.js
  api/close_contact_report/handlers.js
  api/close_contact_report/index.js
  api/close_contact_report/package.json
  api/close_contact_report/route_prerequesites.js
  api/close_contact_report/routes.js
  api/close_contact_report/validations/input.js
  api/helpers.js
  api/index.js
  helpers/constant.js
  helpers/custom.js
  helpers/filter/closecontactfilter.js
  models/CloseContact.js
  models/CloseContactReport.js
  models/CloseContactReportHistory.js
  models/index.js
  services/close_contact.js
  services/close_contact_report.js
  services/close_contact_report_histories.js
  services/index.js
Labels: enhancement

#310 add new column and parsing sort
  models/Case.js
  services/cases.js
  services/unit.js
Labels: bug, enhancement

#313 add date column in section close contact
  models/Case.js
  models/CloseContact.js
Labels: enhancement

#311 Refactor Model
  api/close_contact/handlers.js
  api/close_contact/route_prerequesites.js
  api/close_contact/routes.js
  api/close_contact/validations/input.js
  api/close_contact_report/handlers.js
  api/close_contact_report/index.js
  api/close_contact_report/package.json
  api/close_contact_report/route_prerequesites.js
  api/close_contact_report/routes.js
  api/close_contact_report/validations/input.js
  api/helpers.js
  api/index.js
  helpers/constant.js
  helpers/filter/closecontactfilter.js
  models/CloseContact.js
  models/CloseContactHistory.js
  models/CloseContactReport.js
  models/index.js
  services/close_contact.js
  services/close_contact_histories.js
  services/close_contact_report.js
  services/close_contact_report_histories.js
  services/index.js
Labels: enhancement

#315 update column cases, closecontact, and history
  models/Case.js
  models/CloseContact.js
  models/History.js
Labels: enhancement

#316 Adjust payload validation based on added 'month' field.
  api/close_contact/routes.js
  api/close_contact/validations/input.js
  helpers/filter/closecontactfilter.js
  models/CloseContact.js
  services/close_contact.js
Labels: enhancement

#319 Only validate if NIK is set. (Allow Null/Empty string)
  models/CloseContact.js
Labels: enhancement

#320 add endpoint create close contact only multiple or single
  api/cases_revamp/handlers.js
  api/cases_revamp/routes.js
  helpers/cases/revamp/handlerpost.js
  services/case_revamp.js
Labels: enhancement

#323 Bug fixing
  helpers/cases/revamp/handlerpost.js
  services/case_revamp.js
  services/cases.js
Labels: bug, enhancement

#328 Epidemiological investigation form
  api/close_contact/validations/input.js
  helpers/pdfmaker.js
  helpers/pdftemplate/components/epidemiological-investigation/close-contact-list.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
  helpers/pdftemplate/components/epidemiological-investigation/diagnosis.js
  helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js
  helpers/pdftemplate/components/epidemiological-investigation/patient-notes.js
  helpers/pdftemplate/layouts/epidemiological-investigation.js
  models/CloseContact.js
  services/cases.js
Labels: enhancement

#338 Added history revamp to JSONFor
  models/History.js
Labels: enhancement

#339 Feature/close contact
  api/close_contact/handlers.js
  api/close_contact/route_prerequesites.js
  api/close_contact/routes.js
  api/close_contact/validations/input.js
  helpers/constant.js
  helpers/custom.js
  helpers/filter/closecontactfilter.js
  models/CloseContact.js
  services/close_contact.js
Labels: enhancement

#341 add new column in schema case and set default value
  models/Case.js
  services/case_revamp.js
Labels: enhancement

#344 Remove creation attributes in Close-Contact details
  models/CloseContact.js
Labels: enhancement

#343 code styling
  .editorconfig
Labels: documentation, enhancement

#345 Added flag 'is_patient_address_same' in close-contact schema.
  api/close_contact/validations/input.js
  models/CloseContact.js
Labels: enhancement

#346 create contact
  api/cases_revamp/handlers.js
  services/case_revamp.js
Labels: bug

#347 populate createdBy
  models/CloseContact.js
  services/close_contact.js
Labels: enhancement

#348 handle single and multiple
  services/case_revamp.js
Labels: bug

#351 add column is_patient_address_same
  models/History.js
Labels: bug

#353 hot fix cannot save history
  services/histories.js
Labels: bug

#355 Hot fix
  api/users/validations/input.js
  services/histories.js
Labels: bug

#368 add new column
  helpers/filter/exportfilter.js
  models/Case.js
  models/History.js
  services/cases.js
Labels: enhancement

#369 remove required stage unused column
  models/History.js
Labels: bug, enhancement

#372 modify sorting
  api/cases/validations/input.js
  helpers/custom.js
  services/cases.js
Labels: bug, enhancement

#373 Dashboard input test
  api/dashboard/handlers.js
  api/dashboard/routes.js
  helpers/sectionnumber.js
  services/dashboard.js
Labels: backend

#374 Dashboard input test
  helpers/filter/casefilter.js
  helpers/sectionnumber.js
Labels: backend

#377 Revamp/dashboard
  api/case_dashboard/handlers.js
  api/case_dashboard/index.js
  api/case_dashboard/package.json
  api/case_dashboard/routes.js
  api/case_dashboard/validations/input.js
  api/index.js
  helpers/constant.js
  models/Case.js
  services/case_dashboard.js
  services/index.js
Labels: enhancement

#381 other locations included in hospital location
  services/case_dashboard.js
Labels: enhancement

#384 fix closecontact aggregate rules
  services/case_dashboard.js
Labels: bug

#385 fix closecontact aggregate rules
  services/case_dashboard.js
Labels: bug

#388 set final_result as required field
  models/Case.js
  models/History.js
Labels: bug, enhancement

#391 Added query sort handler
  services/cases.js
Labels: bug, hotfix

#392 Added query sort handler
  services/cases.js
Labels: bug, hotfix

#393 export new final result
  helpers/constant.js
  helpers/filter/exportfilter.js
Labels: bug, enhancement

#395 Improved PE-Form
  api/cases/handlers.js
  helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
  helpers/pdftemplate/components/epidemiological-investigation/close-contact-list.js
  helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js
Labels: enhancement, hotfix

#394 Improved PE-Form
  api/cases/handlers.js
  helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
  helpers/pdftemplate/components/epidemiological-investigation/close-contact-list.js
  helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js
Labels: enhancement, hotfix

#400 Added API revamp/case-verifications
  api/cases_verifications/handlers.js
  api/cases_verifications/index.js
  api/cases_verifications/package.json
  api/cases_verifications/routes.js
  api/index.js
Labels: enhancement

#402 added case check exception (except deleted)
  services/case_revamp.js
Labels: hotfix

#401 Handle if caseId isn't found.
  api/cases/route_prerequesites.js
  api/cases_verifications/routes.js
Labels: enhancement

#404 Hotfix/cases revamp
  services/case_revamp.js
Labels: hotfix
