Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2020-09, with the labels that each got.

#485 inject last history
  api/index.js
  api/inject/handlers.js
  api/inject/index.js
  api/inject/package.json
  api/inject/routes.js
  services/index.js
  services/inject.js
Labels: bug

#504 Feature/epidemiological investigation form
  helpers/pdftemplate/components/epidemiological-investigation/close-contact-list.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
Labels: enhancement

#505 finish feature history-travell
  api/history_travel/handlers.js
  api/history_travel/index.js
  api/history_travel/package.json
  api/history_travel/routes.js
  api/index.js
  models/History.js
  services/history_travel.js
  services/index.js
  services/inject.js
Labels: enhancement

#507 leftover joi validation in additional field
  api/close_contact/validations/input.js
Labels: bug

#510 feature public place crud
  api/index.js
  api/public_place/handlers.js
  api/public_place/index.js
  api/public_place/package.json
  api/public_place/routes.js
  models/History.js
  services/index.js
  services/public_place.js
Labels: enhancement

#509 Multiple insert data
  services/rdt.js
Labels: enhancement

#508 Multiple insert data
  services/rdt.js
Labels: enhancement

#517 [pe-form] adjust based on revamped schema
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
  helpers/pdftemplate/components/epidemiological-investigation/inspection-information.js
Labels: enhancement

#516 [daily-report] adjust based on revamped schema
  helpers/reports/handler.js
  helpers/reports/transformer.js
Labels: enhancement

#515 minor fixing
  api/history_travel/handlers.js
  api/history_travel/routes.js
  api/local_transmission/handlers.js
  api/local_transmission/routes.js
  api/public_place/handlers.js
  api/public_place/routes.js
  models/Case.js
  models/History.js
  services/history_travel.js
  services/local_transmission.js
  services/public_place.js
Labels: bug

#519 Bug fixing
  services/areas.js
Labels: bug

#520 remove id_case in delete filter
  api/history_travel/handlers.js
  api/history_travel/routes.js
  api/local_transmission/handlers.js
  api/local_transmission/routes.js
  api/public_place/handlers.js
  api/public_place/routes.js
  services/history_travel.js
  services/local_transmission.js
  services/public_place.js
Labels: bug

#522 Inspection support
  api/index.js
  api/inspection_support/handlers.js
  api/inspection_support/index.js
  api/inspection_support/package.json
  api/inspection_support/routes.js
  services/index.js
  services/inspection_support.js
Labels: backend

#523 Feature/closecontact
  api/close_contact/handlers.js
  api/close_contact/routes.js
  helpers/closecontact/handler.js
  helpers/custom.js
  models/Case.js
  services/cases.js
  services/close_contact.v2.js
  services/index.js
Labels: enhancement

#524 Feature/cases primer
  models/Case.js
Labels: backend, enhancement

#525 Feature/cases exposure
  api/case_exposure/handlers.js
  api/case_exposure/index.js
  api/case_exposure/package.json
  api/case_exposure/routes.js
  api/index.js
  services/case_exposure.js
  services/index.js
Labels: backend, enhancement

#526 fix code update
  services/inspection_support.js
Labels: bug

#527 bug fix inject data input test
  services/rdt.js
Labels: bug

#528 Feature/searching
  api/index.js
  api/search/handlers.js
  api/search/index.js
  api/search/package.json
  api/search/routes.js
  services/case_exposure.js
  services/history_travel.js
  services/index.js
  services/local_transmission.js
  services/public_place.js
  services/search.js
Labels: enhancement

#530 Injectdata code fix
  models/RdtHistory.js
  services/rdt.js
Labels: bug

#531 api inject data input test
  api/inject/handlers.js
  api/inject/routes.js
  services/inject.js
Labels: backend

#529 Fix code
  models/RdtHistory.js
  services/rdt.js
Labels: bug

#556 Feature/export case
  helpers/constant.js
  helpers/custom.js
  helpers/filter/exportfilter.js
  models/History.js
  services/cases.js
Labels: enhancement

#562 Feature/dashboard v2
  api/case_dashboard/handlers.js
  api/case_dashboard/routes.js
  api/case_dashboard/validations/input.js
  helpers/aggregate/demographicaggregate.js
  helpers/aggregate/groupaggregate.js
  helpers/aggregate/summaryaggregate.js
  helpers/aggregate/topaggregate.js
  helpers/aggregate/visualizationaggregate.js
  helpers/custom.js
  helpers/filter/casefilter.js
  helpers/rolecheck.js
  services/case_dashboard.js
Labels: enhancement
