Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2020-12, with the labels that each got.

#714 handle concat string ifnull
  services/search.js
Labels: bug

#711 codeclimate-week3(task-3):
  api/cases/route_prerequesites.js
  api/helpers.js
  api/rdt/route_prerequesites.js
  services/rdt_histories.js
  utils/conditional.js
Labels: code quality

#720 refactor pe-form contacttracing
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
  helpers/pdftemplate/components/epidemiological-investigation/inspection-information.js
  helpers/pdftemplate/components/epidemiological-investigation/symptoms.js
  helpers/pdftemplate/helper.js
Labels: code quality

#733 improvement(daily-report):
  api/reports/handlers.js
  api/reports/index.js
  api/reports/routes.js
  helpers/reports/handler.js
  helpers/reports/transformer.js
  services/reports.js
Labels: enhancement

#734 improvment manifest root
  config/manifest.js
Labels: bug

#735 improvment manifest root
  config/manifest.js
Labels: bug

#737 Feature/improvement dashboard summary cases
  helpers/aggregate/func/filter.js
  helpers/aggregate/summaryaggregate.js
Labels: backend, bug

#716 feature/notification
  .env-example
  api/users/handlers.js
  api/users/routes.js
  config/config.js
  helpers/constant.js
  helpers/custom.js
  helpers/dictionary/id.json
  helpers/fcm.js
  helpers/filter/notificationFilter.js
  helpers/firebase.js
  helpers/notification.js
  models/Notification.js
  models/User.js
  models/UserDevice.js
  models/index.js
  services/cases.js
  services/cases.v2.js
  services/cases_verifications.js
  services/notifications.js
  services/users.js
Labels: WIP, rework

#739 Feature/multiple update
  api/cases/handler_explode.js
  api/cases/index.js
  api/cases/routes_explode.js
  api/history_travel/handlers.js
  api/inspection_support/handlers.js
  api/local_transmission/handlers.js
  api/public_place/handlers.js
  helpers/request/index.js
  services/cases_other.js
  services/index.js
Labels: documentation, enhancement

#749 add rs jabar query
  services/areas.js
Labels: bug

#743 dashboard test result
  api/dashboard/handlers.js
  api/dashboard/routes.js
  helpers/aggregate/func/filter.js
  helpers/aggregate/func/lookup.js
  helpers/aggregate/groupaggregate.js
  helpers/aggregate/rdtage.js
  helpers/aggregate/rdtaggregate.js
  helpers/aggregate/rdtgender.js
  helpers/export/README.md
  helpers/filter/casefilter.js
  helpers/filter/mapfilter.js
  helpers/sectionnumber.js
  models/Rdt.js
  services/dashboard.js
Labels: backend, code quality, data, enhancement

#755 multiple update to clinic histories
  services/cases_other.js
Labels: bug, enhancement

#761 Feature/notifications: added API user notif summary
  api/notifications/handlers.js
  api/notifications/routes.js
  services/notifications.js
Labels: enhancement

#764 Feature/improvement pemeriksaan penunjang
  api/logistics/handlers.js
  models/Case.js
  services/inspection_support.js
Labels: enhancement

#765 Deployment to Production
  api/logistics/handlers.js
  models/Case.js
  services/inspection_support.js
Labels: release
