Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2020-10, with the labels that each got.

#566 Feature/export cases
  helpers/aggregate/groupaggregate.js
  helpers/custom.js
  helpers/filter/exportfilter.js
Labels: data, enhancement, mongodb schema

#569 export cases
  helpers/filter/casefilter.js
  helpers/filter/exportfilter.js
  services/cases.js
Labels: bug

#571 Feature/export cases
  helpers/filter/exportfilter.js
Labels: enhancement

#573 finish report excell hisories
  api/histories/handlers.js
  api/histories/routes.js
  api/index.js
  helpers/filter/exportfilter.js
  helpers/filter/historyfilter.js
  services/histories.js
Labels: enhancement

#576 Feature/closecontact (refactor prerequesites)
  api/cases_closecontact/route_prerequesites.js
  services/cases_closecontact.js
Labels: enhancement, refactor

#575 Added flagging on event pull + refactor
  helpers/cases/flagger.js
  models/Case.js
  services/cases_closecontact.js
Labels: enhancement, refactor

#577 try refactoring duplicate
  api/case_exposure/handlers.js
  api/helpers.js
  helpers/historycheck.js
Labels: refactor, refactoring duplicate code

#578 Feature/dashboard v2
  api/case_dashboard/handlers.js
  api/case_dashboard/routes.js
  api/case_exposure/handlers.js
  api/case_exposure/routes.js
  helpers/aggregate/ageaggregate.js
  helpers/aggregate/demographicaggregate.js
  helpers/aggregate/func/filter.js
  helpers/aggregate/func/index.js
  helpers/aggregate/genderaggregate.js
  helpers/aggregate/globalcondtion.js
  helpers/aggregate/recapaggregate.js
  helpers/aggregate/summaryaggregate.js
  helpers/aggregate/visualizationaggregate.js
  helpers/aggregate/weeklyaggregate.js
  helpers/custom.js
  helpers/routes/index.js
  services/case_dashboard.js
Labels: enhancement, refactoring duplicate code

#580 refactor api handler&routes
  api/cases/routes.js
  api/cases_closecontact/handlers.js
  api/cases_closecontact/route_prerequesites.js
  api/cases_closecontact/routes.js
Labels: refactor, similar blocks of code

#583 corrected check condition on update
  api/cases/route_prerequesites.js
Labels: bug

#586 change reference column
  .codeclimate.yml
  helpers/constant.js
  helpers/custom.js
  helpers/filter/exportfilter.js
Labels: bug

#591 Feature/closecontact
  helpers/cases/prerequesites.js
  helpers/closecontact/handler.js
  helpers/filter/relatedfilter.js
  models/Case.js
  models/attributes.js
  services/case_related.js
  services/cases.v2.js
  services/cases_closecontact.js
Labels: enhancement

#593 naming as global helper
  helpers/cases/global.js
  services/cases_closecontact.js
Labels: refactor

#596 Hot-fix insert input test
  services/rdt.js
Labels: bug, hotfix

#597 Hot-fix insert input test
  services/rdt.js
Labels: bug, hotfix

#594 explode function
  helpers/aggregate/demographicaggregate.js
  helpers/aggregate/func/index.js
  helpers/aggregate/genderaggregate.js
  helpers/aggregate/globalcondtion.js
  helpers/aggregate/groupaggregate.js
  helpers/aggregate/visualizationaggregate.js
Labels: refactor

#598 update dashboard response
  api/cases/routes.js
  api/cases/validations/output.js
  helpers/aggregate/groupaggregate.js
  helpers/aggregate/summaryaggregate.js
Labels: bug, enhancement, refactor

#600 [Codeclimate Test]:areas
  api/areas/handlers.js
  api/areas/routes.js
  api/case_exposure/handlers.js
  api/case_exposure/index.js
  api/case_exposure/package.json
  api/case_exposure/routes.js
  api/cases/validations/input.js
  api/index.js
  helpers/dictionary/index.js
  helpers/request/index.js
  services/case_exposure.js
  services/index.js
Labels: code quality, refactor

#606 wrong column
  helpers/aggregate/demographicaggregate.js
Labels: bug

#608 add filter by criteria
  helpers/aggregate/demographicaggregate.js
  helpers/aggregate/func/index.js
  helpers/aggregate/recapaggregate.js
Labels: bug
