Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2021-02, with the labels that each got.

#815 change rule import(final_result):
  helpers/cases/sheet/validator.js
Labels: bug

#819 UP devops k8s jacloud
  .dockerignore
  Dockerfile.release
  Jenkinsfile.jacloud
  api/dashboard/handlers.js
  api/dashboard/routes.js
  api/index.js
  api/logistics/handlers.js
  api/logistics/index.js
  api/logistics/package.json
  api/logistics/routes.js
  api/users/handlers.js
  api/users/routes.js
  helpers/aggregate/groupaggregate.js
  helpers/aggregate/rdtage.js
  helpers/aggregate/rdtaggregate.js
  helpers/aggregate/rdtgender.js
  helpers/aggregate/rdtlocation.js
  helpers/constant.js
  kubernetes/production/configmap-pelaporan-api.yaml
  kubernetes/production/deployment-pelaporan-api.yaml
  kubernetes/production/secret-pelaporan-api.yaml
  kubernetes/production/service-pelaporan-api.yaml
  services/dashboard.js
Labels: enhancement, hotfix

#822 Feature/improve k8s
  config/config.js
  helpers/aggregate/groupaggregate.js
  helpers/aggregate/rdtage.js
  helpers/aggregate/rdtaggregate.js
  helpers/aggregate/rdtgender.js
  helpers/aggregate/rdtlocation.js
  helpers/filter/date.js
  services/rdt.js
Labels: backend, hotfix
