Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2021-01, with the labels that each got.

#766 codeclimate(week5):
  api/case_related/handlers.js
  helpers/aggregate/topaggregate.js
  helpers/custom.js
  helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
  services/case_dashboard.js
Labels: code quality

#768 Remove uppercase on notif message
  helpers/notification.js
Labels: enhancement

#772 notification(improvement):
  helpers/filter/notificationFilter.js
Labels: enhancement

#774 improvement dashboard(hasil-test)
  helpers/aggregate/groupaggregate.js
  helpers/aggregate/rdtaggregate.js
Labels: bug, enhancement

#775 change number to date
  helpers/aggregate/groupaggregate.js
  helpers/aggregate/rdtaggregate.js
  helpers/constant.js
Labels: enhancement

#773 refactoring (services, handlers):
  api/index.js
  api/logistics/handlers.js
  api/logistics/index.js
  api/logistics/package.json
  api/logistics/routes.js
  api/users/handlers.js
  api/users/routes.js
Labels: code quality

#810 Test k8s staging
  config/config.js
Labels: backend
