Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2021-04, with the labels that each got.

#889 Integrasi Labkes Pelaporan
  .env-example
  helpers/constant.js
  helpers/dictionary/id.json
  helpers/integration/index.js
  helpers/integration/splitpayloadlabkes.js
  helpers/integration/splitpayloadpikobar.js
  helpers/integration/timeout.js
  helpers/notification.js
  integration/index.js
  integration/labkes_pelaporan.js
  integration/lapor_mandiri.js
  services/integration.js
Labels: backend

#905 Hotfix/verif worker
  services/cases_verifications.js
Labels: bug

#909 Feature/caching map related temp
  services/case_related.js
Labels: enhancement

#916 Feature/caching dashboard temp
  helpers/filter/redis.js
  services/case_dashboard.js
Labels: enhancement

#853 Refactoring rate B,C,D
  api/cases_transfers/handlers.js
  api/cases_transfers/routes.js
  api/close_contact/routes.js
  api/users/routes.js
  helpers/constant.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
Labels: refactor, refactoring duplicate code

#955 update queue(improvement):
  package-lock.json
  services/queue.js
Labels: enhancement

#956 maintainability pelaporan(codeclimate):
  api/cases/route_prerequesites.js
  api/helpers.js
  api/rdt/handlers.js
  api/rdt/routes.js
  helpers/custom.js
  helpers/filter/casefilter.js
  helpers/filter/notificationFilter.js
  helpers/paginate.js
  services/case_related.js
  services/cases.js
  services/rdt.js
  services/users.js
Labels: code quality

#969 refactoring (day2):
  api/cases/routes.js
  helpers/pdftemplate/components/epidemiological-investigation/treatment.js
  helpers/rdt/custom.js
  services/inject.js
  services/rdt.js
Labels: code quality
