Repository jabardigitalservice/pikobar-pelaporan-backend, pull requests merged in 2021-05, with the labels that each got.

#971 change checkout
  jest.config.json
  services/queue.js
  utils/pagination.js
Labels: bug

#979 Hotfix/change package
  package-lock.json
  package.json
Labels: enhancement

#978 update package(version):
  package-lock.json
  package.json
Labels: enhancement

#992 Merge dev master
  Makefile
  api/close_contact/handlers.js
  api/close_contact/index.js
  api/close_contact/package.json
  api/close_contact/route_prerequesites.js
  api/close_contact/routes.js
  api/close_contact/validations/input.js
  api/index.js
  api/rdt/handlers.js
  api/rdt/route_prerequesites.js
  api/rdt/routes.js
  helpers/constant.js
  helpers/email/index.js
  helpers/filter/search.js
  helpers/job/README.md
  helpers/job/export_xlsx.js
  helpers/job/index.js
  helpers/rolecheck.js
  services/queue.js
  services/rdt.js
  services/rdt_others.js
Labels: bug, enhancement

#1021 Development
  .env-example
  api/cases/handlers.js
  config/config.js
  helpers/cases/global.js
  helpers/email/index.js
  helpers/filter/casefilter.js
  helpers/filter/userfilter.js
  helpers/integration/splitpayloadlabkes.js
  helpers/job/index.js
  helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
  helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
  helpers/pdftemplate/components/epidemiological-investigation/diagnosis.js
  integration/index.js
  package-lock.json
  package.json
  services/cases.js
  services/integration.js
  services/queue.js
  services/users.js
  test/user.test.js
Labels: backend
